### ISSUE TITLE
Replace "Beckn" logo with ONDC logo

### ISSUE THREAD

**Issue by BLR-0118** [beckn/ondc-test-bap-community#3]
For testbap, replace "Beckn" logo with ONDC logo

**Comment by BLR-0118** [comment]
@vrushalijatti

**Comment by pramodkvarma** [comment]
Reference apps should NOT be hard coding any logo including ONDC. Why is it not configurable? Whoever wants to build the app binary can configure and build. @core-wg-admin  @vrushalijatti
